/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// export default sidebars;

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {

//   tutorialSidebar: [

//     {type: 'autogenerated',  dirName: '.'},
//   ],
  // docs:[
  //   'intro',
  //   'installation',
  //   'setup',
  //   'usage',
  //   {
  //     type: 'category',
  //     link: {
  //       type: 'generated-index',
  //     },
  //     collapsed:false,
  //     items: [
  //       'filters/merge',

  //     ]
  //   }
  // ]
//};

//export default sidebars;
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  pickingToolSidebar: [
    {
      type: 'category',
      label: 'Picking Tool',
      items: [
        'intro', 
        'install',
        'setup',
        'usage',
        {
          type: 'category',
          label: 'Filters',
          items: [
            'filters/merge',
            'filters/duplicate',
            'filters/sandd',
            'filters/trim',
          ],
        },
     
      ],
    },
  ],
  gitHubSidebar: [
    {
      type: 'category',
      label: 'GitHub',
      items: [
        'github/intro_git', 
        'github/access_git',
        'github/setup_ide',
        'github/setup_ssh',
        {
          type:'category',
          label: 'Working',
          items: [
            'github/process/process_git',
            'github/process/branch_git',
          ],
        },

      ],
    },
  ],
  portalSidebar: [
    {
      type: 'category',
      label: 'Portal',
      items: [
        'portal/portal_intro', 
        'portal/account',
        'portal/newsfeed',
        'portal/frac',
        'portal/ss',
        'portal/plot',
        'portal/reports',
     
      ],
    },
  ],
};

export default sidebars;
